import {StyleSheet} from 'react-native';
import {Colors, Metrics, Fonts} from '../themes';

const RequestListScreenLtrStyle = StyleSheet.create({
  container: {
    zIndex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: Colors.black,
  },
  title: {
    fontFamily: "helvetica !important",
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderBottomColor: "#000000",
    paddingTop: 10,
    paddingBottom: 10,
  },
  title_text: {
    fontSize: Fonts.h5,
    fontWeight: '600',
    color: Colors.orange,
    marginRight: 20,
  },
  select_view: {
    width: '100%',
    paddingLeft: 15,
    paddingBottom: 5,
    paddingTop: 5,
    marginBottom: 5,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    borderBottomWidth: 1,
    borderBottomColor: "#000000",
  },
  list: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    backgroundColor: Colors.black,
  },
  list_item: {
    paddingLeft: 5,
    paddingRight: 5,
    borderBottomWidth: 1,
    borderBottomColor: "#000000",
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    backgroundColor: Colors.black,
  },
  title_contents: {
    width: "100%",
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 5,
    paddingBottom: 15,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center'
  },
  list_item_title: {
    fontSize: 14,
    color: Colors.black,
    fontWeight: 'normal',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center'
  },
  offers_count: {
    color: Colors.yellow,
    marginLeft: 12,
    fontSize: 14,
    fontWeight: 'bold',
  },
  list_item_date_time: {
    fontSize: Fonts.medium,
    color: Colors.white,
    fontWeight: "bold",
    paddingLeft: 10,
    paddingTop: 15,
  },
  list_item_details: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
  },
  list_item_address: {
    width: '51%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignContent: 'center',
    padding: 10,
    paddingTop: 0,
    paddingRight: 5,
    paddingBottom: 5,
  },
  list_item_address_title: {
    fontSize: Fonts.regular,
    fontWeight: 'bold',
    paddingBottom: 5,
  },
  list_item_address_value: {
    fontSize: Fonts.small,
    fontWeight: 'normal',
    color: Colors.white,
  },
  list_item_additional_details: {
    width: '49%',
    padding: 0,
    paddingRight: 5,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignContent: 'center',
  },
  list_item_detail: {
    paddingTop: 10,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
  },
  list_item_detail_title: {
    fontSize: Fonts.medium,
    fontWeight: 'bold',
    color: Colors.black,
  },
  list_item_detail_value: {
    paddingTop: 2,
    fontSize: Fonts.small,
    color: Colors.darkGrey,
  },
});

export default RequestListScreenLtrStyle;
