const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_ERROR = 'LOGOUT_ERROR';
export { LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_ERROR, LOGOUT_ERROR, LOGOUT_REQUEST, LOGOUT_SUCCESS };
